# Generated by Django 4.2.3 on 2023-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brands', models.TextField(max_length=100, null=True)),
                ('nutrition_grade_fr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
