# Generated by Django 4.2.3 on 2023-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='brands',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nutrition_grade_fr',
            field=models.CharField(null=True),
        ),
    ]
