# Generated by Django 4.2.3 on 2023-07-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_produit_countries_produit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tag',
        ),
    ]
