# Generated by Django 4.2.3 on 2023-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='product_name_fr',
            field=models.CharField(null=True),
        ),
    ]
