# Generated by Django 4.2.3 on 2023-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_produit_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pnns_groups_1',
            field=models.CharField(null=True),
        ),
    ]
